### PR TITLE
Fixed bugs (for Sketch 43)

### PR DESCRIPTION
**Pull request by girafic**
- duplicate layer
- pull left/up and push down/right

### CODE REVIEW

**Comment by illustree** [comment]
maaaan you the best!!! @girafic for president

**Comment by ghost** [comment]
Who's merging it ?

**Comment by getflourish** [comment]
<3 Thank you @girafic for fixing this action. Duplicate was one of the first things that made me start this repo back in 2014 and I’m happy to see that the urge is big enough that you’ve made a pro-active move to fix it! I’m out-of-date with latest API changes, so I really appreciate this.
 
Merged @illustree @edward-battistini

**Comment by ghost** [comment]
thank you so much guys ! this is amazing !

**Pull request merged**
